### ISSUE TITLE
this is s test issue

### ISSUE THREAD

**Issue by giodegas** [EMICVL/testRepo#5]
Here you can describe problems, bugs, or new feature requests

**Comment by NataliyaVasylieva** [comment]
Thank you.

2015-06-14 15:14 GMT+03:00 Giovanni De Gasperis notifications@github.com:

**Comment by Nikolay-Odessa** [comment]
Ok! Thank you.

**Comment by giodegas** [comment]
This is just for test. 
Please use issues associated to your repositories also to track bugs.

**Comment by SergeyAfonin** [comment]
Hi! What type of license do you recommend for MODELS. Thank you.

2015-06-18 13:06 GMT+03:00 Giovanni De Gasperis notifications@github.com:

**Comment by giodegas** [comment]
let's not discuss this issue here, but on the proper issue were it was originated.

**Comment by giodegas** [comment]
I am closing this test issue. No more replies here please.
